tinyMCE.addI18n('en.wce',{
	language : "Language",
	note_desc : "Add note",
	note_edit_desc : "Edit note",
	correction_desc : "Add correction(s)",
	correction_edit_desc : "Edit correction(s)",
	break_desc : "Add break",
	break_edit_desc : "Edit break",
	gap_desc : "Add gap",
	gap_edit_desc : "Edit gap",
	number_desc : "Add number",
	number_edit_desc : "Edit number",
	note_title : "Please insert a note",
	note_type : "Note type",
	editorial : "Editorial",
	transcriber : "Transcriber",
	canon : "Canon reference",
	other : "Other",
	note : "Note",
	note_data : "Information about the note",
	break_title : "Please specify the break",
	break_data : "Information about the break",
	break_type : "Type of break",
	linebreak : "Line break",
	columnbreak : "Column break",
	pagebreak : "Page break",
	quire : "Quire",
	number : "Number",
	running_title : "Running title",
	alignment : "Alignment",
	alignment_lj : "Left-justified",
	alignment_cj : "Centre-justified",
	alignment_rj : "Right-justified",
	alignment_indent : "Indented",
	alignment_hanging : "Hanging line",
	recto : "r",
	verso : "v",
	papyrus_recto : "x",
	papyrus_verso : "y",
	pb_type : "Type of page break",
	pb_page : "Page",
	pb_folio: "Folio",
	formework : "Forme work",
	fw_pagenumber: "Page number",
	fw_quiresignature : "Quire signature",
	fw_running : "Running title",
	fw_chapter_title : "Chapter title",
	fw_chapter_number : "Chapter number",
	fw_lectionary_title : "Lectionary title",
	fw_lectionary_incipit : "Lectionary incipit",
	fw_lectionary_explicit : "Lectionary explicit",
	fw_colophon : "Colophon",
	fw_ammonian : "Ammonian Section number",
	fw_eusebian : "Eusebian canon",
	fw_euthaliana : "Euthaliana",
	fw_gloss : "Gloss",
	reading_title : "Please insert a reading",
	reading_data : "Information about the reading",
	reading_type : "Type of reading",
	correction : "Correction",
	commentary : "Commentary reading",
	alternative : "Alternative reading",
	corrector_name : "Corrector name (hand)",
    firsthand : "First hand",
	blank_firsthand : "Blank first hand ",
	blank_correction : "Blank correction",
	corrector : "Corrector",
	corrector_text : "Corrector text",
	corrector_place : "Place of correction",
	unidentified_corrector : "Unidentified corrector",
	editorial_note: "Editorial Note",
	corr_overwritten : "Overwritten text",
	corr_above : "Above line",
	corr_below : "Below line",
	corr_lmargin : "Left margin",
	corr_rmargin : "Right margin",
	corr_top : "Page top margin",
	corr_bottom : "Page bottom margin",
	corr_elsewhere : "Elsewhere",
	deletion : "Method of deletion",
	del_erased : "Erased",
	del_underline : "Underline",
	del_underdot : "Underdot",
	del_striketrough : "Strikethrough",
	del_vertical_line : "Vertical line",
	gap_title : "Please specify the gap",
	gap_data : "Information about the gap",
	gap_type: "Writing material is",
	lacuna : "absent.",
	illegible_text : "present.",
	space : "Blank spaces",
	other : "Other",
	othertype : "User-defined type",
	reason : "Reason",
	damage : "Damage",
	hole : "Hole",
	stain : "Stain",
	erasure : "Erasure",
	otherdamage : "Other damage",
	number : "Number",
	agent : "Agent",
	agent_water: "Water",
	agent_fire: "Fire",
	unit : "Unit",
	unit_line : "Line",
	unit_char : "Char",
	unit_page : "Page",
	unit_quire: "Quire",
	extent : "Extent",
	hand : "Hand",
	suppliedsource : "Supplied source",
	number_title : "Please specify the number",
	number_type : "Type of number",
	number_data : "Information about the number",
	gap : "Gap",
	supplied : "Supplied text",
	mark_as_supplied : "Mark as supplied",
	unclear : "Unclear (doubtful) reading",
	unclear_text_title : "Please specify the unclear text",
	tt_corrname : "Name of the corrector",
	tt_corrtext : "Text of the correction",
	charmap_greek_only : "Greek only",
	charmap_latin_only : "Latin only",
	charmap_all : "All glyphs",
	unclear_text_info : "Please specify the uncertain letters" ,
	unclear_text_data : "Information about the uncertain letters" ,
	poor_image : "Poor image",
	faded_ink : "Faded ink",
	damage_to_page : "Damage to page",
	obscured_in_image : "Obscured in image",
	supplied_source_title : "Please specify the supplied source",
	supplied_source_data : "Information about the supplied source",
	supplied_source : "Supplied source",
	na27 : "NA27",
	TR : "TR",
	paratext : "Paratext",
	paratext_title : "Specify paratext",
	paratext_data : "Information about paratext",
	position : "Position",
	position_top : "top margin",
	position_bottom : "bottom margin",
	position_left : "left margin",
	position_right : "right margin",
	position_above : "above line",
	position_below : "below line",
	position_thispoint : "this point in text",
	alignment_l : "Left",
	alignment_r : "Right",
	alignment_c : "Center",
	abbr_title : "Please specify abbreviation",
	abbr_data : "Information about abbreviation",
	abbr_type : "Type of abbreviation",
	abbr_nomenSacrum : "Nomen sacrum",
	abbr_numeral : "Numeral",
	abbr_addOverline : "Add overline to highlighted text",
	spaces_title : "Please specify the blank spaces",
	spaces_data : "Information about the blank spaces",
	reading_list : "List of corrections",
	metadata_title : "Options for meta data",
	meta_tab_title : "Title statement",
	meta_tab_publication : "Publication statement",
	meta_tab_source : "Source description",
	meta_tab_encoding : "Encoding",
	meta_title_data : "Title statement",
	meta_title : "Document title (long)",
	meta_title_document : "Document title (short)",
	meta_title_collection : "Title of collection",
	meta_title_work : "Title of work",
	meta_title_short : "Short title",
	meta_title_respStmt : "Other data",
	meta_resp : "Created by",
	meta_funder : "Funder",
	meta_sponsor : "Sponsor",
	meta_editorialStmt : "Editorial statement",
	meta_edition_version : "Version",
	meta_edition_date : "Date",
	meta_publicationStmt : "Publication statement",
	meta_publisher : "Publisher",
	meta_publication_date : "Publication date",
	meta_publication_availability : "Availibility",
	meta_sourceDesc : "Source Description",
	meta_msDesc_country : "Country",
	meta_msDesc_settlement : "Settlement",
	meta_msDesc_repository : "Repository",
	meta_msDesc_idno : "ID",
	meta_msDesc_msName : "Manuscript name",
	meta_editorialDecl : "Editorial practise declaration",
	meta_encoding_panel : "Encoding information",
	meta_projectDesc : "Project description",
	meta_encodingDesc : "Encoding description",
	meta_revisionDesc : "Revision description",
	meta_tab_general : "Misc",
	meta_general : "Misc settings",
	empty_other : "Please enter text for all &quot;other&quot; fields",
});
