tinyMCE.addI18n('en.wce',{
	New: "New",
	language : "Language",
	note_desc : "Add note",
	note_edit_desc : "Edit note",
	correction_desc : "Add correction(s)",
	correction_edit_desc : "Edit correction(s)",
	break_desc : "Add break",
	break_edit_desc : "Edit break",
	gap_desc : "Add gap",
	gap_edit_desc : "Edit gap",
	number_desc : "Add number",
	number_edit_desc : "Edit number",
	note_title : "Please insert a note",
	note_type : "Note type",
	editorial : "Editorial note",
	transcriber : "Transcriber query",
	canon : "Canon reference",
	changeOfHand : "Change of hand",
	other : "Other",
	note : "Note",
	note_data : "Information about the note",
	newHand : "Identifier for new hand",
	break_title : "Please specify the break",
	break_data : "Information about the break",
	break_type : "Type of break",
	linebreak : "Line break",
	columnbreak : "Column break",
	pagebreak : "Page break",
	quire : "Quire",
	number : "Number",
	none : "None",
	alignment : "Alignment",
	alignment_lj : "Left-justified",
	alignment_cj : "Centre-justified",
	alignment_rj : "Right-justified",
	alignment_indent : "Indented",
	alignment_hanging : "Hanging line",
	facs : "URL to digital image",
	recto : "recto",
	verso : "verso",
	papyrus_fibre_h : "\u2002\u2192",
	papyrus_fibre_v : "\u2002\u2191",
	pb_type : "Type of page break",
	pb_position : "Position",
	pb_hyphen : "Previous page ends with hyphenated word",
	fibre_type : "Papyrus fibre",
	pb_page : "Page",
	pb_folio: "Folio",
	formework : "Forme work",
	covered : "Number of lines covered",
	text : "Text or number (as written on page)",
	number_attribute : 'Number (as used for XML attribute "n")',
	number_calculate : "Calculate number automatically",
	numeral : "Corresponding number",
	fw_commentary_text: "Commentary text",
	fw_pagenumber: "Page number (as written)",
	fw_quiresignature : "Quire signature",
	fw_runningtitle : "Running title",
	fw_chapter_title : "Chapter title",
	fw_chapter_number : "Chapter number",
	fw_lectionary_title : "Lectionary title",
	fw_lectionary_incipit : "Lectionary incipit",
	fw_lectionary_explicit : "Lectionary explicit",
	fw_colophon : "Colophon",
	fw_ammonian : "Ammonian Section number",
	fw_eusebian : "Eusebian canon",
	fw_euthaliana : "Euthaliana",
	fw_gloss : "Gloss",
	fw_stichoi: "Stichoi",
	firsthand_reading : "First hand reading",
	reading_title : "Please insert a reading",
	reading_data : "Information about the reading",
	reading_type : "Type of reading",
	correction : "Correction",
	commentary : "Commentary reading",
	alternative : "Alternative reading",
	corrector_name : "Corrector name (hand)",
    firsthand : "First hand",
	blank_firsthand : "Blank first hand",
	blank_correction : "Total deletion",
	corrector : "Corrector",
	corrector_text : "Corrector text",
	corrector_place : "Place of correction",
	unidentified_corrector : "(Unidentified) corrector",
	editorial_note: "Editorial Note",
	corr_not_applicable : "Not applicable", 
	deletion : "Method of deletion",
	del_erased : "Erased",
	del_underline : "Underline",
	del_underdot : "Underdot",
	del_striketrough : "Strikethrough",
	del_vertical_line : "Vertical line",
	gap_title : "Please specify the gap",
	gap_data : "Information about the gap",
	gap_type: "Writing material is",
	lacuna : "Lacuna (parchment is absent)",
	illegible_text : "Illegible (parchment is present)",
	space : "Blank spaces",
	other : "Other",
	othertype : "User-defined type",
	reason : "Reason",
	damage : "Damage",
	hole : "Hole",
	stain : "Stain",
	erasure : "Erasure",
	otherdamage : "Other damage",
	agent : "Agent",
	agent_water: "Water",
	agent_fire: "Fire",
	unit : "Unit",
	unit_line : "Line",
	unit_char : "Char",
	unit_page : "Page",
	unit_quire: "Quire",
	extent : "Extent",
	hand : "Hand",
	suppliedsource : "Supplied source",
	number_title : "Please specify the number",
	number_type : "Type of number",
	number_data : "Information about the number",
	gap : "Gap",
	supplied : "Supplied text",
	mark_as_supplied : "Mark as supplied",
	unclear : "Unclear (doubtful) reading",
	unclear_text_title : "Please specify the unclear text",
	tt_corr_deletion : "Hold down SHIFT to select ranges of options; CTRL (apple key) for multiple options",
	tt_corrtext : "Text of the correction",
	charmap_greek_only : "Greek only",
	charmap_latin_only : "Latin only",
	charmap_all : "All glyphs",
	unclear_text_info : "Please specify the uncertain letters" ,
	unclear_text_data : "Information about the uncertain letters" ,
	poor_image : "Poor image",
	faded_ink : "Faded ink",
	damage_to_page : "Damage to page",
	obscured_in_image : "Obscured in image",
	supplied_source_title : "Please specify the supplied source",
	supplied_source_data : "Information about the supplied source",
	supplied_source : "Supplied source",
	na27 : "NA28",
	TR : "TR",
	paratext : "Marginalia",
	paratext_title : "Specify marginalia",
	paratext_data : "Information about marginalia",
	position : "Position",
	position_pagetop : "Page top margin",
	position_pagebottom : "Page bottom margin",
	position_pageleft : "Page left margin",
	position_pageright : "Page right margin",
	position_coltop : "Column top margin",
	position_colbottom : "Column bottom margin",
	position_colleft : "Column left margin",
	position_colright : "Column right margin",
	position_lineleft : "Line left margin",
	position_lineright : "Line right margin",
	position_above : "Above line",
	position_below : "Below line",
	position_thispoint : "This point in text",
	position_elsewhere : "Elsewhere",
	position_overwritten : "Overwritten text",
	alignment_l : "Left",
	alignment_r : "Right",
	alignment_c : "Center",
	abbr_title : "Please specify abbreviation",
	abbr_data : "Information about abbreviation",
	abbr_type : "Type of abbreviation",
	abbr_nomenSacrum : "Nomen sacrum",
	abbr_numeral : "Numeral",
	abbr_addOverline : "Add overline to highlighted text",
	spaces_title : "Please specify the blank spaces",
	spaces_data : "Information about the blank spaces",
	reading_list : "List of corrections",
	metadata_title : "Options for meta data",
	meta_tab_title : "Title statement",
	meta_tab_publication : "Publication statement",
	meta_tab_source : "Source description",
	meta_tab_encoding : "Encoding",
	meta_title_data : "Title statement",
	meta_title : "Document title (long)",
	meta_title_document : "Document title (short)",
	meta_title_collection : "Title of collection",
	meta_title_work : "Title of work",
	meta_title_short : "Short title",
	meta_title_respStmt : "Other data",
	meta_resp : "Created by",
	meta_funder : "Funder",
	meta_sponsor : "Sponsor",
	meta_editorialStmt : "Editorial statement",
	meta_edition_version : "Version",
	meta_edition_date : "Date",
	meta_publicationStmt : "Publication statement",
	meta_publisher : "Publisher",
	meta_publication_date : "Publication date",
	meta_publication_availability : "Availibility",
	meta_sourceDesc : "Source Description",
	meta_msDesc_country : "Country",
	meta_msDesc_settlement : "Settlement",
	meta_msDesc_repository : "Repository",
	meta_msDesc_idno : "ID",
	meta_msDesc_msName : "Manuscript name",
	meta_msDesc_altIdentifier : "Alternative Identifier",
	type : "Typ",
	meta_editorialDecl : "Editorial practise declaration",
	meta_encoding_panel : "Encoding information",
	meta_projectDesc : "Project description",
	meta_encodingDesc : "Encoding description",
	meta_revisionDesc : "Revision description",
	meta_tab_general : "Misc",
	meta_general : "Misc settings",
	empty_other : "Please enter text for all required and all &quot;other&quot; fields",
	empty_number : "Please enter a number (used as attribute &quot;n&quot;)",
	save : 'Your changes have not been saved yet.\nClick "OK" to save them or "Cancel" to discard changes.',
	capitals_data: 'Information about capitals',
	capitals_height : 'Height of the capitals',
	verse_insert : 'Insert verse number: ',
	verse_remove : 'Remove the following verse(s): ',
	inscriptio_insert : 'Insert inscriptio',
	subscriptio_insert : 'Insert subscriptio'
});
